### ISSUE TITLE
Server ignores port specifed in config

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/2Keys#11]
Server ignores a port set in config:
Config snippet:
```yml
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.50
    port: 8080
```

Output:
```
server info Server now listenning on port 9090
```
