### ISSUE TITLE
Up and down functions do not work

### ISSUE THREAD

**Issue by codemicro** [Gum-Joe/2Keys#24]
Hello,

My `config.yml` has this in it
```
$NUM_ENTER&:
        type: multi
        func:
          down: pressPTT
          up: releasePTT
```
however, no action is triggered on a keypress. The two functions work fine on their own keys, and I have ensure I updated both the software for the detector and for the server.
