### ISSUE TITLE
Register.sh is broken

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/2Keys#8]
When using >1 Keyboard register.sh only registers 1:
![screenshot 60](https://user-images.githubusercontent.com/12299307/48641109-9d84de00-e9d0-11e8-8aa8-5134c1a953eb.png)
Config:
```yml
name: pi3
keyboards:
  keyboard_1:
    path: /dev/input/by-id/usb-Logitech_Gaming_Keyboard_G810_166A37573236-event-kbd
    dir: ./Keyboard_1
    root: index.ahk
    hotkeys:
      N: SendN
  keyboard_2:
    path: /dev/input/by-id/usb-Logitech_G513_Carbon_Tactile_105E376A3437-event-kbd
    dir: ./Keyboard_2
    root: index.ahk
    hotkeys:
      N: SendN
addresses:
  detector: 192.168.0.100
  server:
    ipv4: 192.168.0.14
    port: 9090
perms:
  ssh: true
```
